name: "extender:stage channel:alpha"

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 1 * * *

jobs:
  test:
    uses: ./.github/workflows/test
    with:
      channel: alpha
    secrets:
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
